const UNIQUE_APP_POSTFIX = 'better-lyrics';

const SESSION_PARAMS = {
    MUSIC_API_READY: 'musicApiReady',
    CURRENT_MUSIC_TAB_ID: 'currentMusicTabId',
};

const AGENT_NAMES = {
    GET_MUSIC_API_STATUS: 'get-music-api-status',
};

const MUSIC_API_SEEKING_INTERVAL = 500;
const MUSIC_API_SEEKING_TIMEOUT = 15000;

export {
    UNIQUE_APP_POSTFIX,
    SESSION_PARAMS,
    AGENT_NAMES,
    MUSIC_API_SEEKING_INTERVAL,
    MUSIC_API_SEEKING_TIMEOUT,
};
